# Generated by Django 4.1 on 2022-10-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('publication', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('is_deleted', models.CharField(default='n', max_length=10)),
            ],
        ),
    ]
