# Generated by Django 4.1 on 2022-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='is_deleted',
            field=models.CharField(default='n', max_length=5),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(default='avail', max_length=10),
        ),
    ]
