# Generated by Django 4.1 on 2022-10-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_books_is_deleted_alter_books_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='publication',
            new_name='type_of_book',
        ),
        migrations.RemoveField(
            model_name='books',
            name='pages',
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
