# Generated by Django 4.1 on 2022-12-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_rename_publication_books_type_of_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssueRecordTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('date_of_issue', models.DateField()),
                ('status', models.CharField(default='Taken', max_length=15)),
            ],
        ),
    ]
